
package drools8;

unit MeasurementUnit;

rule "will execute per each Measurement having ID color"
when
	/measurements[ id == "color", $colorVal : val ]
then
	controlSet.add($colorVal);
end

rule "Delete red"
when
	$redMeasurement: /measurements[ id == "color", this.val=="red" ]
then
  delete($redMeasurement);
end


query FindColor
    $m: /measurements[ id == "color" ]
end

query FindColorRed
    $m: /measurements[ id == "color" , val=="red"]
end



rule "Delete all but one measurement for color with blue"
enabled true
when 
	$blueMeasurement: /measurements[ id == "color", this.val=="blue" ]
	$blueMeasurement2: /measurements[ id == "color", this.val=="blue" ]
  
then
  delete ($blueMeasurement);
  System.out.println("testing");
end




rule "testing the rule without the when part"
when 
then
System.out.println("I run without the when condition");

end
